"use client";
import { ChevronLeft, ChevronRight, ImageIcon } from "lucide-react";
import { useReducedMotion, motion } from "framer-motion";
import { useState } from "react";
export type GalleryImage = { id: string; url: string; altText: string };
export function ProductGallery({ images, title }: { images: GalleryImage[]; title: string }) {
  const gallery = images.length ? images : [{ id: "placeholder-1", url: "", altText: `نمای اصلی ${title}` }, { id: "placeholder-2", url: "", altText: `نمای کابین ${title}` }, { id: "placeholder-3", url: "", altText: `جزئیات فنی ${title}` }];
  const [active, setActive] = useState(0); const reduceMotion = useReducedMotion(); const current = gallery[active]; const move = (direction: number) => setActive((active + direction + gallery.length) % gallery.length);
  return <div aria-label={`گالری تصاویر ${title}`}><div className="relative overflow-hidden rounded-card bg-gradient-to-br from-navy-900 to-blue-600"><motion.div key={current.id} initial={reduceMotion ? false : { opacity: 0.35, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.25 }} className="grid aspect-[4/3] place-items-center text-white" role="img" aria-label={current.altText}><ImageIcon className="h-20 w-20 text-cyan-300" strokeWidth={1.25} /><span className="absolute bottom-5 rounded-full bg-navy-900/70 px-4 py-2 text-sm backdrop-blur">{current.altText}</span></motion.div>{gallery.length > 1 && <><button type="button" onClick={() => move(-1)} aria-label="تصویر قبلی" className="absolute start-4 top-1/2 -translate-y-1/2 rounded-full bg-white/90 p-2 text-navy-900 focus-visible:ring-2 focus-visible:ring-cyan-500"><ChevronRight /></button><button type="button" onClick={() => move(1)} aria-label="تصویر بعدی" className="absolute end-4 top-1/2 -translate-y-1/2 rounded-full bg-white/90 p-2 text-navy-900 focus-visible:ring-2 focus-visible:ring-cyan-500"><ChevronLeft /></button></>}</div><div className="mt-3 grid grid-cols-3 gap-3">{gallery.map((image, index) => <button type="button" key={image.id} onClick={() => setActive(index)} aria-label={`نمایش ${image.altText}`} aria-current={index === active} className={`grid aspect-[4/3] place-items-center rounded-button border bg-navy-700 text-cyan-300 transition ${index === active ? "border-cyan-500 ring-2 ring-cyan-500/30" : "border-navy-900/10 opacity-70 hover:opacity-100"}`}><ImageIcon className="h-7 w-7" /></button>)}</div></div>;
}
