import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { Nav, Footer, Section, Card, Badge } from "@/components/ui";
import { ContactForm } from "@/components/contact-form";
import { ProductGallery } from "@/components/product-gallery";
import { money } from "@/lib/utils";
export const revalidate = 600;
export async function generateStaticParams() { const products = await db.product.findMany({ where: { isActive: true }, select: { slug: true } }); return products.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: { slug: string } }) { const product = await db.product.findUnique({ where: { slug: params.slug } }); return { title: product?.title || "محصول", description: product?.shortDesc }; }
export default async function Detail({ params }: { params: { slug: string } }) {
  const product = await db.product.findUnique({ where: { slug: params.slug }, include: { images: { orderBy: { order: "asc" } } } }); if (!product?.isActive) notFound(); const specs = product.specs as Record<string, string | number>;
  return <><Nav /><Section><div className="grid items-start gap-10 lg:grid-cols-2"><ProductGallery images={product.images} title={product.title} /><div className="lg:sticky lg:top-28"><Badge>{product.category === "ELEVATOR" ? "آسانسور" : "قطعه تخصصی"}</Badge><h1 className="mt-4 text-4xl font-extrabold leading-tight">{product.title}</h1>{product.subtype && <p className="mt-3 font-medium text-cyan-500">{product.subtype}</p>}<p className="mt-6 leading-8 text-ink-900/75">{product.longDesc}</p><div className="mt-7 rounded-card bg-white p-5 shadow-sm"><span className="text-sm text-ink-900/60">قیمت</span><b className="mt-1 block text-xl text-blue-600">{money(product.price)}</b></div><a href="#quote" className="mt-6 inline-flex w-full justify-center rounded-button bg-gradient-to-l from-cyan-500 to-blue-600 px-7 py-4 font-bold text-white shadow-lg sm:w-auto">درخواست پیش‌فاکتور</a></div></div><div className="mt-16 grid items-start gap-10 lg:grid-cols-2"><Card><h2 className="text-2xl font-bold">مشخصات فنی</h2><p className="mt-2 text-sm text-ink-900/60">مشخصات نهایی متناسب با شرایط پروژه قابل سفارشی‌سازی است.</p><dl className="mt-5 overflow-hidden rounded-button border border-navy-900/10">{Object.entries(specs).map(([key, value], index) => <div className={`grid grid-cols-2 gap-4 px-4 py-3 ${index % 2 === 0 ? "bg-paper-50" : "bg-white"}`} key={key}><dt className="font-bold text-navy-900">{key}</dt><dd>{String(value)}</dd></div>)}</dl></Card><Card className="scroll-mt-28"><div id="quote" className="scroll-mt-28"><p className="text-sm font-bold text-cyan-500">مشاوره تخصصی پروژه</p><h2 className="mb-2 mt-1 text-2xl font-bold">درخواست پیش‌فاکتور</h2><p className="mb-5 text-sm leading-7 text-ink-900/60">نام محصول به‌صورت خودکار همراه درخواست شما ثبت می‌شود.</p><ContactForm productId={product.id} source="PRODUCT" /></div></Card></div></Section><div className="fixed inset-x-0 bottom-0 z-40 border-t border-navy-900/10 bg-white/95 p-3 backdrop-blur lg:hidden"><a href="#quote" className="block rounded-button bg-gradient-to-l from-cyan-500 to-blue-600 p-3 text-center font-bold text-white">درخواست پیش‌فاکتور {product.title}</a></div><Footer /></>;
}
