import Link from "next/link";
import { Prisma, ProductCategory } from "@prisma/client";
import { db } from "@/lib/db";
import { Nav, Footer, Section } from "@/components/ui";
import { ProductCard } from "@/components/product-card";
export const revalidate = 600;
export const metadata = { title: "محصولات", description: "فهرست آسانسورها و قطعات تخصصی تابان نورد" };
type SearchParams = { category?: string; min?: string; max?: string; q?: string; spec?: string; value?: string };
export default async function Products({ searchParams }: { searchParams: SearchParams }) {
  const category = Object.values(ProductCategory).includes(searchParams.category as ProductCategory) ? (searchParams.category as ProductCategory) : undefined;
  const min = searchParams.min ? Number(searchParams.min) : undefined; const max = searchParams.max ? Number(searchParams.max) : undefined;
  const where: Prisma.ProductWhereInput = { isActive: true, category, price: min !== undefined || max !== undefined ? { gte: Number.isFinite(min) ? min : undefined, lte: Number.isFinite(max) ? max : undefined } : undefined, OR: searchParams.q ? [{ title: { contains: searchParams.q, mode: "insensitive" } }, { subtype: { contains: searchParams.q, mode: "insensitive" } }, { shortDesc: { contains: searchParams.q, mode: "insensitive" } }] : undefined };
  const products = await db.product.findMany({ where, orderBy: [{ isFeatured: "desc" }, { createdAt: "desc" }] });
  const specKey = searchParams.spec?.trim().toLocaleLowerCase("fa"); const specValue = searchParams.value?.trim().toLocaleLowerCase("fa");
  const items = products.filter((product) => { if (!specKey && !specValue) return true; return Object.entries(product.specs as Record<string, unknown>).some(([key, value]) => (!specKey || key.toLocaleLowerCase("fa").includes(specKey)) && (!specValue || String(value).toLocaleLowerCase("fa").includes(specValue))); });
  const hasFilters = Object.values(searchParams).some(Boolean);
  return <><Nav /><Section><div className="max-w-3xl"><p className="font-bold text-cyan-500">راهکارهای مهندسی تابان</p><h1 className="mt-2 text-4xl font-extrabold">محصولات و قطعات</h1><p className="mt-4 leading-8 text-ink-900/70">بر اساس دسته‌بندی، بازه قیمت یا مشخصات فنی، گزینه مناسب پروژه خود را پیدا کنید.</p></div><form className="my-8 grid gap-4 rounded-card border border-navy-900/10 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-3" aria-label="فیلتر محصولات"><label className="text-sm font-bold">جستجو<input name="q" defaultValue={searchParams.q} placeholder="نام یا نوع محصول" className="mt-2 w-full rounded-button border p-3 font-normal focus-visible:ring-2 focus-visible:ring-cyan-500" /></label><label className="text-sm font-bold">دسته‌بندی<select name="category" defaultValue={searchParams.category ?? ""} className="mt-2 w-full rounded-button border bg-white p-3 font-normal"><option value="">همه دسته‌ها</option><option value="ELEVATOR">آسانسور</option><option value="SPARE_PART">قطعات</option></select></label><label className="text-sm font-bold">حداقل قیمت<input name="min" defaultValue={searchParams.min} type="number" min="0" placeholder="تومان" className="mt-2 w-full rounded-button border p-3 font-normal" /></label><label className="text-sm font-bold">حداکثر قیمت<input name="max" defaultValue={searchParams.max} type="number" min="0" placeholder="تومان" className="mt-2 w-full rounded-button border p-3 font-normal" /></label><label className="text-sm font-bold">نام مشخصه<input name="spec" defaultValue={searchParams.spec} placeholder="مثلاً ظرفیت یا سرعت" className="mt-2 w-full rounded-button border p-3 font-normal" /></label><label className="text-sm font-bold">مقدار مشخصه<input name="value" defaultValue={searchParams.value} placeholder="مثلاً ۶۳۰ یا EN 81" className="mt-2 w-full rounded-button border p-3 font-normal" /></label><div className="flex flex-wrap items-center gap-3 sm:col-span-2 lg:col-span-3"><button className="rounded-button bg-gradient-to-l from-cyan-500 to-blue-600 px-7 py-3 font-bold text-white">اعمال فیلتر</button>{hasFilters && <Link href="/products" className="rounded-button border border-navy-900/20 px-6 py-3 font-bold text-navy-900">پاک کردن فیلترها</Link>}<span className="me-auto text-sm text-ink-900/60">{items.length.toLocaleString("fa-IR")} محصول</span></div></form><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map((product) => <ProductCard key={product.id} p={product} />)}</div>{!items.length && <div className="rounded-card border border-navy-900/10 bg-white p-10 text-center"><h2 className="text-xl font-bold">محصولی مطابق فیلترها یافت نشد</h2><p className="mt-3 text-ink-900/60">فیلترها را تغییر دهید یا برای انتخاب محصول با کارشناسان ما تماس بگیرید.</p><Link href="/products" className="mt-5 inline-block font-bold text-blue-600">نمایش همه محصولات</Link></div>}</Section><Footer /></>;
}
